export const EXERCISES = [
  {
    id: 1,
    title: 'Morning Cardio Walk',
    category: 'diabetes_friendly',
    difficulty: 'beginner',
    duration: 30,
    caloriesBurn: 150,
    equipment: 'None',
    description: 'A gentle morning walk perfect for managing blood sugar levels. Walking after meals can significantly reduce post-meal blood sugar spikes and improve insulin sensitivity over time.',
    imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400',
    instructions: [
      'Warm up for 5 minutes with slow, easy walking',
      'Gradually increase pace to a moderate, comfortable speed',
      'Keep heart rate at 60–70% of your maximum',
      'Swing arms naturally and maintain good posture',
      'Stay hydrated — carry a water bottle with you',
      'Cool down last 5 minutes by slowing your pace',
    ],
    safetyTips: [
      'Check blood sugar before starting if you are diabetic',
      'Carry fast-acting glucose in case of hypoglycemia',
      'Wear comfortable, supportive footwear',
      'Avoid walking in extreme heat or cold without preparation',
    ],
  },
  {
    id: 2,
    title: 'Full Body Strength Training',
    category: 'strength',
    difficulty: 'intermediate',
    duration: 45,
    caloriesBurn: 320,
    equipment: 'Dumbbells, Barbell',
    description: 'Complete strength workout targeting all major muscle groups. Builds lean muscle mass, improves metabolism, and enhances insulin sensitivity for long-term blood sugar management.',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400',
    instructions: [
      'Start with 5 minutes of dynamic stretching to warm up',
      'Perform squats: 3 sets × 12 reps with controlled movement',
      'Dumbbell rows: 3 sets × 10 reps each arm',
      'Push-ups or bench press: 3 sets × 12 reps',
      'Rest 60 seconds between each set',
      'Finish with a 5-minute cool-down and static stretches',
    ],
    safetyTips: [
      'Never sacrifice form for heavier weight',
      'Have a spotter for heavy barbell exercises',
      'Breathe out on the exertion phase of each lift',
      'Stop if you feel sharp joint pain',
    ],
  },
  {
    id: 3,
    title: 'Yoga for Flexibility',
    category: 'yoga',
    difficulty: 'beginner',
    duration: 40,
    caloriesBurn: 120,
    equipment: 'Yoga mat',
    description: 'Relaxing yoga session to improve flexibility, reduce stress hormones, and promote mindfulness. Stress reduction is particularly important for blood sugar management in diabetics.',
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    instructions: [
      'Find a quiet, comfortable space and lay out your mat',
      'Begin with 5 minutes of deep breathing to center yourself',
      'Move through Cat-Cow pose (10 repetitions)',
      'Hold Downward Dog for 30 seconds, rest, repeat 3×',
      'Warrior I and II poses: 30 seconds each side',
      'End with 5 minutes of Savasana (corpse pose)',
    ],
    safetyTips: [
      'Never force your body into a position',
      'Use blocks or straps if poses feel too intense',
      'Inform instructor of any injuries or limitations',
      'Stay hydrated before and after the session',
    ],
  },
  {
    id: 4,
    title: 'HIIT Cardio Blast',
    category: 'cardio',
    difficulty: 'advanced',
    duration: 25,
    caloriesBurn: 400,
    equipment: 'None',
    description: 'High intensity interval training to maximize calorie burn in minimal time. HIIT has been shown to significantly improve cardiovascular health and insulin sensitivity.',
    imageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400',
    instructions: [
      'Warm up for 5 minutes with light jogging and dynamic stretches',
      'Sprint at 90% effort for 30 seconds',
      'Active rest: walk or slow jog for 30 seconds',
      'Repeat sprint/rest cycle 8–10 times',
      'Monitor heart rate — should reach 85–90% max during sprints',
      'Cool down for 5 minutes with easy walking and stretching',
    ],
    safetyTips: [
      'Not recommended for beginners — build base fitness first',
      'Diabetics: monitor blood sugar closely before and after',
      'Stop immediately if you feel chest pain or dizziness',
      'Limit to 3 sessions per week maximum to avoid overtraining',
    ],
  },
  {
    id: 5,
    title: 'Low Impact Aerobics',
    category: 'diabetes_friendly',
    difficulty: 'beginner',
    duration: 35,
    caloriesBurn: 180,
    equipment: 'None',
    description: 'Gentle aerobic exercises ideal for diabetics, seniors, and beginners. These low-impact movements improve cardiovascular health without stressing the joints.',
    imageUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400',
    instructions: [
      'Start with 5 minutes of easy marching in place',
      'Side steps: step side to side for 2 minutes',
      'Standing bicycle kicks: 3 sets of 20',
      'Step touches with arm raises: 3 minutes',
      'Heel-to-toe walking for balance: 2 minutes',
      'Cool down with gentle neck and shoulder rolls',
    ],
    safetyTips: [
      'Check blood sugar before and after exercise',
      'Keep a snack nearby in case of low blood sugar',
      'Wear supportive shoes to protect feet',
      'Stay seated if feeling lightheaded at any point',
    ],
  },
  {
    id: 6,
    title: 'Core Stability Workout',
    category: 'strength',
    difficulty: 'intermediate',
    duration: 30,
    caloriesBurn: 200,
    equipment: 'Mat',
    description: 'Target your core muscles for better stability, posture, and reduced back pain. A strong core improves performance in all other exercise types and daily activities.',
    imageUrl: 'https://images.unsplash.com/photo-1549060279-7e168fcee0c2?w=400',
    instructions: [
      'Start with a 3-minute warm-up: light marching and hip circles',
      'Plank hold: 3 × 30–60 seconds with proper form',
      'Dead bug exercise: 3 sets × 10 reps each side',
      'Bird-dog: 3 sets × 12 alternating reps',
      'Pallof press (if band available): 3 × 10 each side',
      'Finish with cat-cow and child\'s pose for 3 minutes',
    ],
    safetyTips: [
      'Never hold your breath during core exercises',
      'Keep lower back pressed to mat during lying exercises',
      'Avoid crunches if you have a herniated disc',
      'Quality of movement is more important than quantity',
    ],
  },
  {
    id: 7,
    title: 'Resistance Band Training',
    category: 'strength',
    difficulty: 'beginner',
    duration: 35,
    caloriesBurn: 220,
    equipment: 'Resistance bands',
    description: 'Effective strength training using resistance bands. Joint-friendly and accessible at home, bands provide variable resistance that\'s excellent for building strength safely.',
    imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400',
    instructions: [
      'Choose the right resistance level — should feel challenging by rep 12',
      'Bicep curls: 3 sets × 15 reps with controlled movement',
      'Banded squats: 3 sets × 15 reps, band above knees',
      'Rows: anchor band, pull elbows back: 3 × 12',
      'Shoulder press: 3 × 12, slow and controlled',
      'Stretch all major muscle groups for 5 minutes after',
    ],
    safetyTips: [
      'Check bands for cracks or wear before each use',
      'Anchor points must be secure before pulling',
      'Control the release — never let band snap back',
      'Start with lighter resistance and progress gradually',
    ],
  },
  {
    id: 8,
    title: 'Swimming Basics',
    category: 'cardio',
    difficulty: 'beginner',
    duration: 45,
    caloriesBurn: 280,
    equipment: 'Pool access',
    description: 'Low-impact full body workout excellent for all fitness levels. Swimming is particularly beneficial for people with joint issues, obesity, or diabetes due to zero impact.',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400',
    instructions: [
      'Warm up with 2 easy laps using any comfortable stroke',
      'Practice freestyle breathing technique: breathe every 3 strokes',
      'Swim 4 laps freestyle with 30-second rest between each',
      'Try 2 laps backstroke for variety',
      'Build distance gradually over multiple sessions',
      'Cool down with 2 slow, easy laps then water stretches',
    ],
    safetyTips: [
      'Never swim alone if you\'re a beginner',
      'Stay in marked lanes and follow pool rules',
      'Diabetics: test blood sugar before entering water',
      'Keep pool-side glucose snack if diabetic',
    ],
  },
  {
    id: 9,
    title: 'Chair Yoga for Seniors',
    category: 'diabetes_friendly',
    difficulty: 'beginner',
    duration: 25,
    caloriesBurn: 80,
    equipment: 'Sturdy chair',
    description: 'Accessible yoga exercises that can be done entirely from a chair. Perfect for seniors, people with limited mobility, or anyone recovering from injury.',
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    instructions: [
      'Sit up straight with feet flat on floor, hip-width apart',
      'Seated cat-cow: arch and round your back slowly × 10',
      'Seated forward bend: hinge at hips, reach toward floor',
      'Seated twist: rotate torso gently each direction × 5',
      'Ankle circles: rotate ankles slowly both directions',
      'End with 3 minutes of seated deep breathing',
    ],
    safetyTips: [
      'Use a stable, non-wheeled chair',
      'Move slowly — sudden movements can cause dizziness',
      'Stop if you feel any sharp pain',
      'Consult doctor before starting if you have severe joint conditions',
    ],
  },
  {
    id: 10,
    title: 'Cycling Intervals',
    category: 'cardio',
    difficulty: 'intermediate',
    duration: 40,
    caloriesBurn: 350,
    equipment: 'Bicycle or stationary bike',
    description: 'Alternating high and low intensity cycling for maximum cardiovascular and metabolic benefit. Interval cycling is highly effective for burning fat and improving endurance.',
    imageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400',
    instructions: [
      'Adjust bike seat and handlebar height before starting',
      'Warm up for 10 minutes at comfortable, easy pace',
      'Increase to hard effort (7/10 intensity) for 2 minutes',
      'Recover at easy pace for 2 minutes',
      'Repeat hard/easy cycles 5–6 times',
      'Cool down for 5 minutes at easy pace, then stretch legs',
    ],
    safetyTips: [
      'Always wear a helmet when cycling outdoors',
      'Start with fewer intervals and build up gradually',
      'Maintain proper cycling posture to avoid back strain',
      'Stay visible if cycling outdoors — use lights and reflectors',
    ],
  },
  {
    id: 11,
    title: 'Balance and Coordination',
    category: 'balance',
    difficulty: 'beginner',
    duration: 20,
    caloriesBurn: 100,
    equipment: 'None (wall for support)',
    description: 'Improve balance, coordination and prevent falls with these targeted exercises. Excellent for seniors, diabetics with neuropathy, and anyone wanting to improve functional fitness.',
    imageUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400',
    instructions: [
      'Stand near a wall or sturdy surface for safety',
      'Single-leg stand: balance on one foot for 30 seconds each',
      'Heel-to-toe walk: place heel directly in front of toe, 10 steps',
      'Side leg raises: 3 × 10 each leg, use wall for balance',
      'Focus on a fixed point on the wall to help with stability',
      'Build up duration and reduce wall support as you improve',
    ],
    safetyTips: [
      'Always perform near a wall or solid support',
      'Never close your eyes during balance exercises alone',
      'Wear shoes with good grip (no slippery socks)',
      'Ask someone to spot you for the first few sessions',
    ],
  },
  {
    id: 12,
    title: 'Pilates Core Flow',
    category: 'flexibility',
    difficulty: 'intermediate',
    duration: 45,
    caloriesBurn: 230,
    equipment: 'Mat',
    description: 'Classic Pilates movements for core strength, flexibility, and body awareness. Pilates develops the deep stabilizing muscles that support the spine and improve posture.',
    imageUrl: 'https://images.unsplash.com/photo-1549060279-7e168fcee0c2?w=400',
    instructions: [
      'Lay on mat, imprint spine by engaging core gently',
      'The Hundred: pump arms 100 times while holding legs at table-top',
      'Roll-up: slowly curl up and roll down, 8 repetitions',
      'Single leg circles: 5 circles each direction per leg',
      'Swimming: alternate lifting opposite arm/leg, 30 seconds',
      'Child\'s pose to finish, hold for 2 minutes breathing deeply',
    ],
    safetyTips: [
      'Quality of movement matters more than speed',
      'Keep neck long and relaxed during all exercises',
      'If you have lower back problems, avoid full roll-up',
      'Breathe with each movement — exhale on effort',
    ],
  },
];

export const CATEGORY_COLORS = {
  diabetes_friendly: { pill: 'bg-green-500/20 text-green-400 border-green-500/20',  label: 'Diabetes Friendly' },
  cardio:            { pill: 'bg-blue-500/20 text-blue-400 border-blue-500/20',      label: 'Cardio' },
  strength:          { pill: 'bg-orange-500/20 text-orange-400 border-orange-500/20',label: 'Strength' },
  yoga:              { pill: 'bg-purple-500/20 text-purple-400 border-purple-500/20',label: 'Yoga' },
  flexibility:       { pill: 'bg-pink-500/20 text-pink-400 border-pink-500/20',      label: 'Flexibility' },
  balance:           { pill: 'bg-cyan-500/20 text-cyan-400 border-cyan-500/20',       label: 'Balance' },
};
